# Generated by Django 6.0.3 on 2026-04-03 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre/Razón Social')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT/ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre/Razón Social')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('persona_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('direccion_fiscal', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('pais', models.CharField(blank=True, default='Guatemala', max_length=50, null=True, verbose_name='País')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Producto')),
                ('no_duca', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. de DUCA')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Compra')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entradas/', verbose_name='Imagen')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('referencia', models.CharField(max_length=50, verbose_name='Referencia (ID Venta/Entrada)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento Inventario',
                'verbose_name_plural': 'Movimientos Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('producto_nombre', models.CharField(max_length=100, verbose_name='Producto')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('ubicacion_origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Origen')),
                ('ubicacion_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Destino')),
                ('tipo', models.CharField(choices=[('cambio_ubicacion', 'Cambio de Ubicación'), ('ajuste', 'Ajuste de Stock'), ('revision', 'Revisión')], max_length=20, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='movimientos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_producto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Producto',
                'verbose_name_plural': 'Movimientos de Productos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PreInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Pre-Inventario',
                'verbose_name_plural': 'Pre-Inventario',
                'unique_together': {('codigo', 'producto', 'categoria', 'proveedor', 'ubicacion')},
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='N° Factura')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('envio', 'Envío')], default='factura', max_length=10)),
                ('tipo_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Abono')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.venta')),
            ],
        ),
    ]
