# Generated by Django 6.0.3 on 2026-04-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinventario',
            name='imagen_catalogo',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/', verbose_name='Imagen para Catálogo'),
        ),
    ]
