# Generated by Django 6.0.3 on 2026-04-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinventario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
