# Generated by Django 6.0.3 on 2026-04-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_direccion_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('anulado', 'Anulado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
