# Generated by Django 6.0.3 on 2026-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='entrada',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='Código de Producto'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='no_duca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. de DUCA'),
        ),
        migrations.AlterField(
            model_name='preinventario',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='Código'),
        ),
    ]
