# Generated by Django 6.0.3 on 2026-05-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_categoria_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT/ID'),
        ),
    ]
