from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('entradas/', views.listar_entradas, name='listar_entradas'),
    path('entradas/crear/', views.crear_entrada, name='crear_entrada'),
    path('entradas/editar/<int:id>/', views.editar_entrada, name='editar_entrada'),
    path('entradas/eliminar/<int:id>/', views.eliminar_entrada, name='eliminar_entrada'),
    path('entradas/exportar/<str:formato>/', views.exportar_reporte, name='exportar_reporte'),
    path('ventas/', views.ventas, name='ventas'),
    path('ventas/historial/', views.historial_ventas, name='historial_ventas'),
    path('ventas/buscar-productos/', views.buscar_productos_venta, name='buscar_productos_venta'),
    path('ventas/buscar-cliente/', views.buscar_cliente, name='buscar_cliente'),
    path('ventas/crear-cliente/', views.crear_cliente_rapido, name='crear_cliente_rapido'),
    path('ventas/finalizar/', views.finalizar_venta, name='finalizar_venta'),
    path('productos/', views.listar_productos, name='listar_productos'),
    path('productos/movimiento/', views.registrar_movimiento_producto, name='registrar_movimiento_producto'),
    path('productos/pdf/', views.exportar_productos_pdf, name='exportar_productos_pdf'),
    path('productos/excel/', views.exportar_productos_excel, name='exportar_productos_excel'),
    path('ventas/detalle/<int:id>/', views.venta_detalle, name='venta_detalle'),
    path('ventas/abonos/<int:id>/', views.venta_abonos, name='venta_abonos'),
    path('ventas/abonos/registrar/', views.registrar_abono, name='registrar_abono'),
    path('ventas/exportar/<str:formato>/', views.exportar_ventas, name='exportar_ventas'),
    path('ventas/detalle/pdf/<int:id>/', views.venta_detalle_pdf, name='venta_detalle_pdf'),
    path('inventario/', views.inventario_general, name='inventario_general'),
    path('inventario/pdf/', views.exportar_inventario_pdf, name='exportar_inventario_pdf'),
    path('inventario/excel/', views.exportar_inventario_excel, name='exportar_inventario_excel'),
    path('clientes/', views.listar_clientes, name='listar_clientes'),
    path('clientes/crear/', views.crear_cliente, name='crear_cliente'),
    path('clientes/editar/<int:id>/', views.editar_cliente, name='editar_cliente'),
    path('clientes/eliminar/<int:id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('clientes/pdf/', views.exportar_clientes_pdf, name='exportar_clientes_pdf'),
    path('clientes/excel/', views.exportar_clientes_excel, name='exportar_clientes_excel'),
    path('proveedores/', views.listar_proveedores, name='listar_proveedores'),
    path('proveedores/crear/', views.crear_proveedor, name='crear_proveedor'),
    path('proveedores/editar/<int:id>/', views.editar_proveedor, name='editar_proveedor'),
    path('proveedores/eliminar/<int:id>/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('proveedores/pdf/', views.exportar_proveedores_pdf, name='exportar_proveedores_pdf'),
    path('proveedores/excel/', views.exportar_proveedores_excel, name='exportar_proveedores_excel'),
    path('catalogo/', views.catalogo, name='catalogo'),
    path('catalogo/pdf/', views.exportar_catalogo_pdf, name='exportar_catalogo_pdf'),
    path('pedidos/catalogo/', views.catalogo_pedidos, name='catalogo_pedidos'),
    path('pedidos/ubicaciones/', views.obtener_ubicaciones_producto, name='obtener_ubicaciones_producto'),
    path('pedidos/checkout/', views.checkout_pedido, name='checkout_pedido'),
    path('pedidos/historial/', views.historial_pedidos, name='historial_pedidos'),
    path('pedidos/detalle/<int:id>/', views.detalle_pedido, name='detalle_pedido'),
    path('pedidos/actualizar-campos/', views.actualizar_campos_pedido, name='actualizar_campos_pedido'),
    path('pedidos/finalizar/<int:id>/', views.finalizar_pedido, name='finalizar_pedido'),
    path('pedidos/actualizar-precio/', views.actualizar_precio_detalle, name='actualizar_precio_detalle'),
    path('pedidos/eliminar-detalle/', views.eliminar_detalle_pedido, name='eliminar_detalle_pedido'),
    path('pedidos/anular/<int:id>/', views.anular_pedido, name='anular_pedido'),
    path('categorias/crear/', views.crear_categoria, name='crear_categoria'),
    path('admin-elcharro/', admin.site.urls),
    path('', include('core.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)